"""empty message

Revision ID: 98bbe3d3aeda
Revises: 51bb4d9a7bfb
Create Date: 2022-05-01 16:25:17.699981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bbe3d3aeda'
down_revision = '51bb4d9a7bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('games', 'video',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('games', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('games', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('games', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'video',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('images')
    # ### end Alembic commands ###
